# This workflow will do a clean install of Java & Maven, start a Sauce Connect tunnel, then run a Java Test suite through that tunnel

name: Swag Labs Sample Java Test with Sauce Connect

on:
  push:
    branches:
      - main
  pull_request:

env:
  SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
  SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
  BUILD_PREFIX: true

jobs:
  build-test-env:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Sauce Connect Action
        uses: saucelabs/sauce-connect-action@v1
        with:
          username: ${{ secrets.SAUCE_USERNAME }}
          accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
          tunnelIdentifier: ciTunnel
          scVersion: 4.6.4

      - name: Run Java Test with SC
          uses: saucelabs/sauce-connect-action@v1
          with:
